export const data = [
    {
        image: 'book1.jpg',
        name:"深入理解计算机系统",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"《深入理解计算机系统》(英文版)主要介绍了计算机系统的基本概念，" +
            "包括最底层的内存中的数据表示、流水线指令的构成、虚拟存储器、编译系统、" +
            "动态加载库，以及用户应用等。书中提供了大量实际操作，可以帮助读者更好地理解程" +
            "序执行的方式，改进程序的执行效率。此书以程序员的视角全面讲解了计算机系统，深入" +
            "浅出地介绍了处理器、编译器、操作系统和网络环境，是这一领域的权威之作。"
    },
    {
        image: 'book3.jpg',
        name:"d",
        price:"144",
        id:"2",
        author:"ssw",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book3.jpg',
        name:"as",
        price:"15",
        id:"3",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123"
    },
];

export const cartData = [
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },
    {
        image: 'book3.jpg',
        name:"d",
        price:"1444444444",
        id:"2",
        author:"ssw",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },
    {
        image: 'book3.jpg',
        name:"as",
        price:"15",
        id:"3",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },
    {
        image: 'book3.jpg',
        name:"as",
        price:"15",
        id:"3",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },
    {
        image: 'book3.jpg',
        name:"as",
        price:"15",
        id:"3",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },
    {
        image: 'book3.jpg',
        name:"as",
        price:"15",
        id:"3",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },    {
        image: 'book3.jpg',
        name:"as",
        price:"15",
        id:"3",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },    {
        image: 'book3.jpg',
        name:"as",
        price:"15",
        id:"3",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
    },
];

export const orderData = [
    {
        image: 'book1.jpg',
        name:"123",
        price:"45.5",
        id:"1",
        author:"123",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
        purchaseTime:"2015-06-05",
    },
    {
        image: 'book3.jpg',
        name:"d",
        price:"144",
        id:"2",
        author:"ssw",
        type:"123",
        inventory:1,
        description:"123",
        amount:"1",
        purchaseTime:"2015-10-05",
    },
];
